simplify_app/urls.py
from django.urls import path

from simplify_app.views import index, UserPasswordChangeView, ChangeUserInfoView, profile, UserLogoutView, \
    UserLoginView, result

app_name = 'simplify_app'

urlpatterns = [
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('<str:pk>', result, name='result'),
    path('', index, name='index'),
]

simplify_url/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simplify_app.urls'))
]

simplify_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Was activated?')

    def get_initial(self):
        return self.username.upper()[:2]

    class Meta(AbstractUser.Meta):
        pass


class SimpleUrl(models.Model):
    original_url = models.URLField(default='', db_index=True, verbose_name='URL to simplify')
    simple_url_id = models.CharField(default='', db_index=True, verbose_name='Simple URL id', max_length=10)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.PROTECT, verbose_name='Creator')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')

    class Meta:
        verbose_name = 'URL'
        verbose_name_plural = 'URLs'
        ordering = ['-created_at']

simplify_app/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.core.exceptions import ValidationError

from .models import User, SimpleUrl
# from .apps import user_registered


# Auth

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(
            attrs={
                "autofocus": True,
                "placeholder": "Username",
                "class": "form-control"
            })

        self.fields['password'].widget = forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "placeholder": "Password",
                "class": "form-control"
            })


# Edit User

class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email address',
                             widget=forms.EmailInput(
                                 attrs={
                                     "placeholder": "Enter Email",
                                     "class": "form-control"
                                 }
                             ))

    def __init__(self, *args, **kwargs):
        super(ChangeUserInfoForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        )
        self.fields['first_name'].widget = forms.TextInput(
            attrs={
                "placeholder": "First Name",
                "class": "form-control"
            }
        )
        self.fields['last_name'].widget = forms.TextInput(
            attrs={
                "placeholder": "Last Name",
                "class": "form-control"
            }
        )

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class UserPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget = forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "autofocus": True,
                "placeholder": "Previous password",
                "class": "form-control"
            }
        )
        self.fields['new_password1'].widget = forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "placeholder": "New password",
                "class": "form-control"
            })
        self.fields['new_password2'].widget = forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "placeholder": "New password confirmation",
                "class": "form-control"
            })


# URL form

class SimpleUrlForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SimpleUrlForm, self).__init__(*args, **kwargs)
        self.fields['original_url'].widget = forms.TextInput(
            attrs={
                "placeholder": "URL to simplify",
                "class": "form-control"
            })

    class Meta:
        model = SimpleUrl
        fields = ('original_url', )
        # widgets = {'user': forms.HiddenInput, 'simple_url': forms.HiddenInput}

simplify_app/views.py
import uuid

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.sites.shortcuts import get_current_site
from django.views.generic import UpdateView
from django.urls import reverse_lazy

from simplify_app.forms import ChangeUserInfoForm, UserPasswordChangeForm, LoginForm, SimpleUrlForm
from simplify_app.models import SimpleUrl, User
from simplify_app.utilities import create_simple_url


# App

def index(request):
    result_link = None
    if request.method == 'POST':
        form = SimpleUrlForm(request.POST)
        if form.is_valid():
            original_url = form.cleaned_data['original_url']
            simple_url_id = create_simple_url(original_url, request.user)
            result_link = 'http://' + get_current_site(request).name + '/' + simple_url_id

    else:
        form = SimpleUrlForm()
    context = {'form': form, 'result_link': result_link}
    return render(request, 'simplify_app/home/index.html', context)


def result(request, pk):
    url = SimpleUrl.objects.get(simple_url_id=pk)
    return redirect(url.original_url)

# Profile

@login_required
def profile(request):
    context = {'urls': SimpleUrl.objects.filter(user=request.user.pk),
               'link_start': 'http://' + get_current_site(request).name + '/'}
    return render(request, 'simplify_app/profile/profile.html', context)


class ChangeUserInfoView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'simplify_app/profile/profile_edit.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('simplify_app:profile')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'simplify_app/profile/profile_password_change.html'
    success_url = reverse_lazy('simplify_app:profile')


# Login

class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = 'simplify_app/authentication/login.html'


class UserLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'simplify_app/home/index.html'

templates/includes/configuration-plugin.html
        <div class="custom-template">
			<div class="title">Settings</div>
			<div class="custom-content">
				<div class="switcher">
					<div class="switch-block">
						<h4>Logo Header</h4>
						<div class="btnSwitch">
							<button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
							<button type="button" class="selected changeLogoHeaderColor" data-color="blue"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="green"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="red"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="white"></button>
							<br/>
							<button type="button" class="changeLogoHeaderColor" data-color="dark2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Navbar Header</h4>
						<div class="btnSwitch">
							<button type="button" class="changeTopBarColor" data-color="dark"></button>
							<button type="button" class="changeTopBarColor" data-color="blue"></button>
							<button type="button" class="changeTopBarColor" data-color="purple"></button>
							<button type="button" class="changeTopBarColor" data-color="light-blue"></button>
							<button type="button" class="changeTopBarColor" data-color="green"></button>
							<button type="button" class="changeTopBarColor" data-color="orange"></button>
							<button type="button" class="changeTopBarColor" data-color="red"></button>
							<button type="button" class="changeTopBarColor" data-color="white"></button>
							<br/>
							<button type="button" class="changeTopBarColor" data-color="dark2"></button>
							<button type="button" class="selected changeTopBarColor" data-color="blue2"></button>
							<button type="button" class="changeTopBarColor" data-color="purple2"></button>
							<button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
							<button type="button" class="changeTopBarColor" data-color="green2"></button>
							<button type="button" class="changeTopBarColor" data-color="orange2"></button>
							<button type="button" class="changeTopBarColor" data-color="red2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Sidebar</h4>
						<div class="btnSwitch">
							<button type="button" class="selected changeSideBarColor" data-color="white"></button>
							<button type="button" class="changeSideBarColor" data-color="dark"></button>
							<button type="button" class="changeSideBarColor" data-color="dark2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Background</h4>
						<div class="btnSwitch">
							<button type="button" class="changeBackgroundColor" data-color="bg2"></button>
							<button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
							<button type="button" class="changeBackgroundColor" data-color="bg3"></button>
							<button type="button" class="changeBackgroundColor" data-color="dark"></button>
						</div>
					</div>
				</div>
			</div>
			<div class="custom-toggle">
				<i class="flaticon-settings"></i>
			</div>
		</div>

        

templates/includes/footer.html
			<footer class="footer">
				<div class="container-fluid">
					<nav class="pull-left">
						<ul class="nav">
							<li class="nav-item">
                                <a class="nav-link" 
                                   target="_blank" 
                                   href="https://github.com/ZhekLu/url-shortener">
									Url Shortener
								</a>
							</li>
						</ul>
					</nav>
					<div class="copyright ml-auto">
                        &copy; <a target="_blank" href="https://github.com/ZhekLu">Eugene</a>
                        - template by <a target="_blank" href="https://appseed.us">AppSeed</a>
					</div>				
				</div>
            </footer>
            

templates/includes/navigation.html
{% load static %}
		<div class="main-header">

			<!-- Logo Header -->
			<div class="logo-header" data-background-color="dark2">

				<a href="{% url 'simplify_app:index' %}" class="logo">
                    <img src="{% static "/assets/img/logo.svg" %}" alt="navbar brand" class="navbar-brand">
				</a>
				<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="icon-menu"></i>
					</span>
				</button>
				<button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
				<div class="nav-toggle">
					<button class="btn btn-toggle toggle-sidebar">
						<i class="icon-menu"></i>
					</button>
				</div>
			</div>
			<!-- End Logo Header -->

            <!-- Navbar Header -->
            <nav class="navbar navbar-header navbar-expand-lg" data-background-color="dark">


				<div class="container-fluid">

					{% block additional_navs %}{% endblock %}

					<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                        <li class="nav-item toggle-nav-search hidden-caret">
							<a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
								<i class="fa fa-search"></i>
							</a>
						</li>
                        <li class="nav-item hidden-caret">
							<a class="nav-link" href="{% url 'simplify_app:index' %}" role="button" aria-expanded="false">
								<i class="fa fa-home"></i>
							</a>
						</li>
                        {% if user.is_authenticated %}
						<li class="nav-item dropdown hidden-caret">
							<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                                <div class="avatar-sm float-left mr-2">
                                    <span class="avatar-title rounded-circle text-white">
                                                    {{ user.get_initial }}
                                    </span>
                                </div>
							</a>
							<ul class="dropdown-menu dropdown-user animated fadeIn">
								<div class="scroll-wrapper dropdown-user-scroll scrollbar-outer" style="position: relative;"><div class="dropdown-user-scroll scrollbar-outer scroll-content" style="height: auto; margin-bottom: 0; margin-right: 0px; max-height: 0px;">
									<li>
										<div class="user-box">
											<div class="avatar-lg">
                                                <span class="avatar-title rounded-circle text-white">
                                                    {{ user.get_initial }}
                                                </span>
                                            </div>
											<div class="u-text">
												<h4>
													{{ user.username }}
												</h4>
												<p class="text-muted">
													{{ user.email }}
												</p>
												<a href="{% url 'simplify_app:profile' %}" class="btn btn-xs btn-secondary btn-sm">View Profile</a>
											</div>
										</div>
									</li>
									<li>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="{% url 'simplify_app:profile' %}">My URLs</a>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="{% url 'simplify_app:profile_change' %}">Account Setting</a>
										<a class="dropdown-item" href="{% url 'simplify_app:password_change' %}">Change Password</a>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="#">Logout</a>
									</li>
								</div><div class="scroll-element scroll-x"><div class="scroll-element_outer"><div class="scroll-element_size"></div><div class="scroll-element_track"></div><div class="scroll-bar ui-draggable ui-draggable-handle"></div></div></div><div class="scroll-element scroll-y"><div class="scroll-element_outer"><div class="scroll-element_size"></div><div class="scroll-element_track"></div><div class="scroll-bar ui-draggable ui-draggable-handle"></div></div></div></div>
							</ul>
						</li>
                        {% endif %}
					</ul>
				</div>
			</nav>
            <!-- End Navbar -->
        </div>

templates/includes/scripts.html
{% load static %}
	<!--   Core JS Files   -->
	<script src="{% static "/assets/js/core/jquery.3.2.1.min.js" %}"></script>
	<script src="{% static "/assets/js/core/popper.min.js" %}"></script>
	<script src="{% static "/assets/js/core/bootstrap.min.js" %}"></script>

	<!-- jQuery UI -->
	<script src="{% static "/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js" %}"></script>
	<script src="{% static "/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js" %}"></script>

	<!-- jQuery Scrollbar -->
	<script src="{% static "/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js" %}"></script>

	<!-- Chart JS -->
	<script src="{% static "/assets/js/plugin/chart.js/chart.min.js" %}"></script>

	<!-- jQuery Sparkline -->
	<script src="{% static "/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js" %}"></script>

	<!-- Chart Circle -->
	<script src="{% static "/assets/js/plugin/chart-circle/circles.min.js" %}"></script>

	<!-- Datatables -->
	<script src="{% static "/assets/js/plugin/datatables/datatables.min.js" %}"></script>

	<!-- Bootstrap Notify -->
	<script src="{% static "/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js" %}"></script>

	<!-- jQuery Vector Maps -->
	<script src="{% static "/assets/js/plugin/jqvmap/jquery.vmap.min.js" %}"></script>
	<script src="{% static "/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js" %}"></script>

	<!-- Sweet Alert -->
	<script src="{% static "/assets/js/plugin/sweetalert/sweetalert.min.js" %}"></script>

	<!-- Atlantis JS -->
    <script src="{% static "/assets/js/atlantis.min.js" %}"></script>

templates/includes/sidebar.html
	{% load static %}
		<!-- Sidebar -->
		<div class="sidebar sidebar-style-2" data-background-color="dark2">
			<div class="sidebar-wrapper scrollbar scrollbar-inner">
				<div class="sidebar-content">

				{% if user.is_authenticated %}
					<div class="user">
						<div class="avatar-sm float-left mr-2">
						    <span class="avatar-title rounded-circle">
                                            {{ user.get_initial }}
                            </span>
                        </div>
						<div class="info">
							<a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
								<span>
									{{ user.username }}
									<span class="user-level">
										{{ user.email }}
									</span>
									<span class="caret"></span>
								</span>
							</a>
							<div class="clearfix"></div>

							<div class="collapse in" id="collapseExample">
								<ul class="nav">
									<li>
										<a href="{% url 'simplify_app:profile' %}">
											<span class="link-collapse">My URLs</span>
										</a>
									</li>
									<li>
										<a href="{% url 'simplify_app:logout' %}">
											<span class="link-collapse">Logout</span>
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
                {% else %}
					<ul class="nav nav-primary">
						<li class="mx-4 mt-2">
                            <a
                               href="{% url 'simplify_app:login' %}"
                               class="btn btn-info btn-block btn-border">
                                <span class="btn-label mr-2"> <i class="fa fa-rocket"></i> </span>Sign In</a>
						</li>
                        <li class="mx-4 mt-2">
                            <a target="_blank"
                               href="#"
                               class="btn btn-block btn-warning btn-border">
                                <span class="btn-label mr-2"> <i class="fa fa-rocket"></i> </span>Registration</a>
						</li>
					</ul>
				{% endif %}

					<ul class="nav nav-primary">
                        <li class="nav-item">
                            <a href="{% url 'simplify_app:index' %}">
                                <i class="fas fa-home"></i>
                                <p>Simplify Url</p>
                            </a>
                        </li>
					</ul>
				</div>
			</div>
		</div>
        <!-- End Sidebar -->

templates/simplify_app/authentication/activation_done.html
{% extends 'layout/base.html' %}


{% load static %}

{% block title %} Activation {% endblock %}

{% block content %}
    <div class="content">
		<div class="page-inner">
			<h4 class="page-title">Activation</h4>
            <h2>User with this name was successfully activated.</h2>
            <h2>You can log in to the site.</h2>
            <a href="{% url 'simplify_app:login' %}"
               class="btn btn-success btn-border btn-lg fw-bold mb-3">Sign In</a>
            <a href="{% url 'simplify_app:index' %}"
               class="btn btn-info btn-border btn-lg fw-bold mb-3">Back to main page</a>
        </div>
    </div>
{% endblock %}

templates/simplify_app/authentication/bad_signature.html
{% extends 'layout/base.html' %}


{% load static %}

{% block title %} Activation {% endblock %}

{% block content %}
    <div class="content">
		<div class="page-inner">
			<h4 class="page-title">Activation</h4>
            <h2>Error during activation.</h2>
            <h2>Activation of user with this name failed. You can try register again.</h2>
            <a href="{% url 'simplify_app:register' %}"
               class="btn btn-warning btn-border btn-lg fw-bold mb-3">Register</a>
            <a href="{% url 'simplify_app:index' %}"
               class="btn btn-info btn-border btn-lg fw-bold mb-3">Back to main page</a>
        </div>
    </div>
{% endblock %}

templates/simplify_app/authentication/logout.html
{% extends 'layout/base.html' %}


{% load static %}

{% block title %}Log out{% endblock %}

{% block content %}
    <div class="content">
		<div class="page-inner">
			<h4 class="page-title">We will be waiting for your return.</h4>
            <a href="{% url 'simplify_app:index' %}"
               class="btn btn-info btn-border btn-lg fw-bold mb-3">Back to main page</a>
        </div>
    </div>
{% endblock %}

templates/simplify_app/authentication/register_done.html
{% extends 'layout/base.html' %}


{% load static %}

{% block title %} Registration {% endblock %}

{% block content %}
    <div class="content">
		<div class="page-inner">
			<h4 class="page-title">Registration</h4>
            <h2>User registration complete.</h2>
            <h2>Check your email address to activate your account.</h2>
            <a href="{% url 'simplify_app:index' %}"
               class="btn btn-info btn-border btn-lg fw-bold mb-3">Back to main page</a>
            <a href="{% url 'simplify_app:login' %}"
               class="btn btn-success btn-border btn-lg fw-bold mb-3">Sign In</a>
        </div>
    </div>
{% endblock %}

templates/simplify_app/authentication/user_is_activated.html
{% extends 'layout/base.html' %}


{% load static %}

{% block title %} Activation {% endblock %}

{% block content %}
    <div class="content">
		<div class="page-inner">
			<h4 class="page-title">Activation</h4>
            <h2>User with this name was activated early.</h2>
            <h2>You can log in to the site.</h2>
            <a href="{% url 'simplify_app:login' %}"
               class="btn btn-success btn-border btn-lg fw-bold mb-3">Sign In</a>
            <a href="{% url 'simplify_app:index' %}"
               class="btn btn-info btn-border btn-lg fw-bold mb-3">Back to main page</a>
        </div>
    </div>
{% endblock %}

templates/simplify_app/home/invalid_url.html
{% extends 'layout/base.html' %}


{% load static %}

{% block title %}Log out{% endblock %}

{% block content %}
    <div class="content">
		<div class="page-inner">
			<h4 class="page-title">Such URL haven't been created yet.</h4>
            <a href="{% url 'simplify_app:index' %}"
               class="btn btn-success btn-border btn-lg fw-bold mb-3">Create new URL</a>
        </div>
    </div>
{% endblock %}

templates/simplify_app/profile/profile.html
{% extends "layout/base.html" %}

{% load static %}

{% block title %} Widgets {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<div class="content">
		<div class="page-inner">
            <!-- Welcome Info -->
			<h4 class="page-title">Profile of
                {% if user.first_name and user.last_name %}
                    {{ user.first_name }} {{ user.last_name }}
                {% else %}
                    {{ user.username }}
                {% endif %}
            </h4>
            <div class="row">
                <div class="col-md-4">
                    <div class="card card-info card-annoucement card-round">
                        <div class="card-body text-center">
                            <div class="card-opening">
                                {% if user.first_name %}
                                Welcome {{ user.first_name }},
                                {% else %}
                                Welcome {{ user.username }},
                                {% endif %}
                            </div>
                            <div class="card-desc">
                                Create beautiful and simple URLs!
                            </div>
                            <div class="card-detail">
                                <a class="btn btn-light btn-rounded" href="{% url 'simplify_app:index' %}">Create URL</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <!-- Picture posts count info -->
					<div class="card card-stats card-round">
						<div class="card-body">
							<div class="row align-items-center">
								<div class="col-icon">
									<div class="icon-big text-center icon-info bubble-shadow-small">
										<i class="flaticon-interface-6"></i>
									</div>
								</div>
								<div class="col col-stats ml-3 ml-sm-0">
									<div class="numbers">
										<p class="card-category">URLs created</p>
										<h4 class="card-title">{{ urls.count }}</h4>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
            </div>
			<!-- User Urls -->
			<h4 class="page-title">Your URLs</h4>
            {% if urls %}
{#                <div class="row">#}
                        <div class="col-md-6 ml-auto mr-auto">
                            <div class="card full-height">
						        <div class="card-body">
                                    {% for url in urls %}
                                    <div class="d-flex">
                                        <div class="flex-1 ml-3 pt-1">
                                            <h3 class="fw-bold mb-1 text-info">
                                                <a href="{{ link_start }}{{ url.simple_url_id }}">
                                                {{ link_start }}{{ url.simple_url_id }}
                                                    <a>
                                            </h3>
                                            <span class="text-muted">{{ url.original_url}}</span>
                                        </div>
                                        <div class="float-right pt-1">
                                        <small class="text-muted">{{ url.created_at }}</small>
                                        </div>
                                    </div>
                                        <div class="separator-solid"></div>
                                    {% endfor %}
						        </div>
					        </div>
						</div>
            {% else %}
            <h2 class="mb-2">You don't have any URLs yet.</h2>
            {% endif %}
		</div>
	</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

	<!-- Atlantis DEMO methods, don't include it in your project! -->
	<script src="{% static "/assets/js/setting-demo.js" %}"></script>
	<script>
		$('#lineChart').sparkline([102,109,120,99,110,105,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: '#177dff',
			fillColor: 'rgba(23, 125, 255, 0.14)'
		});

		$('#lineChart2').sparkline([99,125,122,105,110,124,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: '#f3545d',
			fillColor: 'rgba(243, 84, 93, .14)'
		});

		$('#lineChart3').sparkline([105,103,123,100,95,105,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: '#ffa534',
			fillColor: 'rgba(255, 165, 52, .14)'
		});

		$('#lineChart4').sparkline([102,109,120,99,110,105,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: 'rgba(255, 255, 255, .5)',
			fillColor: 'rgba(255, 255, 255, .15)'
		});

		$('#lineChart5').sparkline([99,125,122,105,110,124,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: 'rgba(255, 255, 255, .5)',
			fillColor: 'rgba(255, 255, 255, .15)'
		});

		$('#lineChart6').sparkline([105,103,123,100,95,105,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: 'rgba(255, 255, 255, .5)',
			fillColor: 'rgba(255, 255, 255, .15)'
		});
	</script>

{% endblock javascripts %}